import React, { useEffect } from 'react';
import { motion } from 'framer-motion';
import { Shield, Lock } from 'lucide-react';
import { useLocation } from 'react-router-dom';
import { US_STATES, DEFAULT_STATE } from '../data/statesData';

export default function LegalSite() {
  const stateCode = localStorage.getItem('provider_state') || localStorage.getItem('detected_state') || 'us';
  const stateData = US_STATES[stateCode] || DEFAULT_STATE;
  const location = useLocation();
  const isPrivacy = location.pathname.includes('privacy');
  const isBaa = location.pathname.includes('baa');
  
  useEffect(() => {
    window.scrollTo(0, 0);
  }, [location.pathname]);

  const title = isBaa ? "Business Associate Agreement (BAA)" : isPrivacy ? "Privacy Policy" : "Terms of Service";

  return (
 <div className="min-h-screen bg-background pt-32 px-4 pb-24">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="max-w-4xl mx-auto">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-emerald-500/30 bg-emerald-500/10 text-emerald-400 font-bold mb-6 text-sm">
           {isBaa ? <Lock className="w-4 h-4"/> : <Shield className="w-4 h-4" />} Legal & Compliance Documentation
        </div>
        
        <h1 className="text-4xl md:text-5xl font-extrabold text-white tracking-tight mb-8">
          {title}
        </h1>
        
 <div className="glass-card py-8 px-4 md:py-12 px-4 text-slate-300 leading-relaxed font-serif text-lg">
          {isBaa ? (
            <>
              <p className="mb-6">This Business Associate Agreement ("BAA") is entered into by and between the {stateData.name} {stateData.facilityType} Provider ("Covered Entity") and Agentic Home Care OS ("Business Associate"), safely provisioning the deployment of the NVIDIA NeMo architecture within an isolated Virtual Private Cloud (VPC).</p>
              <h2 className="text-2xl font-bold text-white mt-8 mb-4 font-sans">1. Scope of PHI Usage</h2>
              <p className="mb-6">To maintain strict compliance with {stateData.complianceLaw} and HIPAA security rules, Protected Health Information (PHI) is processed deterministically. At no point is PHI used to train global, multi-tenant foundational AI models.</p>
              <h2 className="text-2xl font-bold text-white mt-8 mb-4 font-sans">2. RCW 74.34 Mandatory Reporter Triggers</h2>
              <p className="mb-6">The system is configured to flag abuse heuristics. The Covered Entity retains ultimate responsibility for acting upon alerts generated by the Interval Watchdog.</p>
            </>
          ) : isPrivacy ? (
            <>
              <p className="mb-6">At Agentic Home Care OS, we consider privacy to be military-grade mandate rather than a secondary feature. Because we serve the highly regulated {stateData.name} {stateData.facilityType} market, our infrastructure design enforces strict ethical boundaries.</p>
              <h2 className="text-2xl font-bold text-white mt-8 mb-4 font-sans">Data Isolation Guarantee</h2>
              <p className="mb-6">Every Provider instance is sandboxed. Resident rosters, hospital discharge notes, and EVV logs processed by the Intake Assistant are structurally partitioned.</p>
            </>
          ) : (
            <>
              <p className="mb-6">By accessing and utilizing the Agentic Home Care OS, you agree to these Terms of Service. This platform is an assisted automation system designed to support RN Delegators, not replace their clinical judgment.</p>
              <h2 className="text-2xl font-bold text-white mt-8 mb-4 font-sans">Compliance Verification</h2>
              <p className="mb-6">While our architecture generates {stateData.regulator} Audit-ready binders, the final verification of compliance with {stateData.complianceLaw} regulations remains the ultimate responsibility of the licensed home provider.</p>
            </>
          )}
        </div>
      </motion.div>
    </div>
  );
}
